version: 2
updates:
  - package-ecosystem: gomod
    directory: "/connect-native"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "theme/dependencies"
  - package-ecosystem: gomod
    directory: "/grpc-checks"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    labels:
      - "theme/dependencies"
